import type { NewsSourceConfig } from "./types";

export const NEWS_SOURCES: NewsSourceConfig[] = [
  {
    name: "Reuters World",
    url: "https://www.reutersagency.com/feed/?best-topics=world&post_type=best",
    homepage: "https://www.reuters.com",
    language: "en",
    region: "Global",
    weight: 1.4,
    categoryHint: "国际",
    enabled: true,
  },
  {
    name: "BBC World",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    homepage: "https://www.bbc.com/news/world",
    language: "en",
    region: "Europe",
    weight: 1.3,
    categoryHint: "国际",
    enabled: true,
  },
  {
    name: "Al Jazeera",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    homepage: "https://www.aljazeera.com",
    language: "en",
    region: "Middle East",
    weight: 1.2,
    categoryHint: "国际",
    enabled: true,
  },
  {
    name: "DW",
    url: "https://rss.dw.com/rdf/rss-en-all",
    homepage: "https://www.dw.com",
    language: "en",
    region: "Europe",
    weight: 1.1,
    categoryHint: "国际",
    enabled: true,
  },
  {
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    homepage: "https://www.theverge.com",
    language: "en",
    region: "Americas",
    weight: 1,
    categoryHint: "科技",
    enabled: true,
  },
  {
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    homepage: "https://techcrunch.com",
    language: "en",
    region: "Americas",
    weight: 1,
    categoryHint: "科技",
    enabled: true,
  },
];
